### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by davipatricio** [davipatricio/darcy#3]
- [ ] General
  - [ ] Add Readme with instructions
  - [ ] Maybe create a wiki with useful information about the project

- [ ] Front-end
  - [x] https://github.com/davipatricio/darcy/pull/2
  - [ ] Refactor `FeedPostMedia` to handle multiple media.
  - [ ] Auth
    - [ ] Localize pages
    - [ ] Handle e-mail authentication
  - [ ] User profiles

- [ ] Back-end
  - [ ] Auth
    - [ ] Handle e-mail authentication
    - [ ] Add support to Google and GitHub OAuth2
  - [ ] Routes
    - [ ] Posts
      - [ ] `GET /posts/[id]` - Returns data of a post or comment
      - [ ] `POST /posts/[id?]` - Creates a new post or comment
      - [ ] `DELETE /posts/[id]` - Deletes a post or comment made by the authenticated user
      - [ ] `POST /posts/[id]/like` - Likes a post
      - [ ] `POST /posts/[id]/repost?content=string?` - Reposts a post or comment, optionally with a content
      - [ ] `DELETE /posts/[id]/like` - Un-likes a post
